apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: jira-to-github-issue-converter
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: web
      dockerfileName: Dockerfile
      publicPort: http
      ports:
        - name: http
          port: 3000